### ISSUE TITLE
What kind of nonsense is this?

### ISSUE THREAD

**Issue by Vladik01-11** [openmultiplayer/vscode-pawn#14]
![Code_kC94VNBjk6](https://github.com/user-attachments/assets/b582f1bd-5b90-4d46-b6af-4e5a4db9c357)

**Comment by AmyrAhmady** [comment]
looks like the extension is reading from YSI and retrieving those macros for auto complete 
https://github.com/pawn-lang/YSI-Includes/blob/fa673344659bce16fc13f0c11151eafbdf7c890f/YSI_Coding/y_inline/y_inline_impl.inc#L2166

You can use this YSI files I guess:
https://github.com/openmultiplayer/vscode-pawn#usage-of-pawnignore

**Comment by Vladik01-11** [comment]
> You can use this YSI files I guess:
> https://github.com/openmultiplayer/vscode-pawn#usage-of-pawnignore

it looks like a crutch, not a solution... 😕

**Comment by AmyrAhmady** [comment]
And what would the solution be? YSI defines macros using #define 
the extension lists #define defines for user to use imagine you have `#define MAX_CUSTOM_GANGZONES 100`

What am I supposed to do with these YSI defines??
