### ISSUE TITLE
Incorrect variable formatting 

### ISSUE THREAD

**Issue by PerseweratywneImponderabilia** [openmultiplayer/vscode-pawn#3]
As discussed on Discord.
Everything works fine when we move the first defined array to the line with `static` or if the first variable isn't an array.

Before:

```
static
bool:a[0],
Float:b[MAX_PLAYERS];
```

After:
```
static
bool:a[0],
                         Float:b[MAX_PLAYERS];
```

**Comment by AmyrAhmady** [comment]
fixed
